[WIP][MIG]school_fees: Migration to v14.
JayVora-SerpentCS/OdooEduERP pull request #189
Opened 2020-09-21 06:00 UTC by ForamSerpentCS

2020-09-21 11:11 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/__manifest__.py
>               'views/school_fees_view.xml',
the data file should define before view.

2020-09-21 11:15 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +                    rec.number = self.env['ir.sequence'].next_by_code(
self.env['ir.sequence'] define outside the for loop

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS requested changes

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/README.rst
> +install 'school', 'account_voucher' module
account_voucher module is not there in odoo14.

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/demo/school_fees_demo.xml
> +            <field name="name">Sport Fees</field>
"Sport(s) Fee"

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +            rec.total_amount = total_amt
Can be done in a single line using inline for loop and sum function

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +                amount += data.total
use inline for loop

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +            self.standard_id = self.student_id.standard_id.id
Please check, remove if self.standard_id = False declartion not require.

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +        for rec in self:
Define journal = rec.journal_id as its used multiple times in code

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +        return super(StudentPayslip, self).write(vals)
Create and write method have the same block of code, Can't we code once and use twice?

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +        return super(StudentPayslip, self).copy(default)
Please check I guess we can eliminate this method and instead use copy=False in field definition.
the default value of the state is already defined as 'draft'

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/models/school_fees.py
> +            rec.register_id.write({'total_amount': rec.total})
Same as above, inline for loop and sum function

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/report/student_fees_register.xml
> +                                <h1 class="text-center">Student Payroll Register</h1>
Student(s) Payroll Register

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/security/security_fees.xml
> +            <field name="name">Parent Fees Record Rule</field>
Parent(s)

2020-09-28 10:05 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/security/security_fees.xml
> +            <field name="name">Student Fees Register Rule</field>
Student(s)

2020-09-29 10:06 UTC, JayVora-SerpentCS commented on school_fees/__manifest__.py
> +    "name": "Fees Management",
edit name

2020-11-04 06:23 UTC, Trivedi-Vacha-SerpentCS requested changes

2020-11-04 06:23 UTC, Trivedi-Vacha-SerpentCS commented on school_fees/report/report_student_fees_register.py
> +        return out_date
No need of out_date variable, direct use 
return indate.strftime("%B") + "-" + indate.strftime("%Y")

2020-11-04 06:40 UTC, Trivedi-Vacha-SerpentCS approved these changes

2020-11-04 10:23 UTC, merged