[WIP][MIG]school_transport: Migration to v14.
JayVora-SerpentCS/OdooEduERP pull request #191
Opened 2020-09-23 13:17 UTC by ForamSerpentCS

2020-09-28 11:25 UTC, Trivedi-Vacha-SerpentCS requested changes

2020-09-28 11:25 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +                trans_student_rec.write({'active': False})
trans_student_rec.active = False

2020-09-29 09:48 UTC, JayVora-SerpentCS commented on school_transport/__manifest__.py
> +    "name": "Transport Management",
Transport Management - A Part of Education ERP

2020-09-29 09:49 UTC, JayVora-SerpentCS commented on school_transport/__manifest__.py
> +    "depends": ["school"],
check for the FLEET compatability. It isa nearfit now.
@AnuKPatel @ForamSerpentCS

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS requested changes

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +        current_date = fields.datetime.today()
fields.Date.today()

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +            trans_student_rec = self.env["transport.participant"].search(
Define self.env objects outside the for loop

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +            trans_regi_rec = self.env["transport.registration"].search(
same as above

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +                trans_regi_rec.write({"state": "cancel"})
trans_regi_rec.state = "cancel"

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +    )
Did not understand the reason of the field name part_name. Here field name should be student_id,

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +    for_month = fields.Integer("Registration For Months")
Change the field name as registration_month

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +    m_amount = fields.Float(
the field name should be monthly_amount

2020-11-24 06:58 UTC, Trivedi-Vacha-SerpentCS commented on school_transport/models/transport.py
> +            invoice.write({"invoice_line_ids": [(0, 0, line_vals)]})
invoice.invoice_line_ids = [(0, 0, line_vals)]

2020-11-24 07:43 UTC, JayVora-SerpentCS commented
@ForamSerpentCS see the latest v14 codes. There are smart one line codes whch will save time.

2020-11-24 11:27 UTC, Trivedi-Vacha-SerpentCS approved these changes

2020-11-24 19:01 UTC, merged